// app/data/accessoriesData.tsx

const accessoriesData = [
  {
    id: 1,
    images: ["/honda-civic-2019.png", "/honda-civic-2019.png", "/honda-civic-2019.png"],
    title: "Alloy Wheels",
    sub_title: "Premium Rims",
    feature1: "Set of 4",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 800",
    sub_price: "PKR 1,000",
    num: "4 Pieces",
    num2: "17 Inch",
    num3: "Aluminum",
    material: "Premium Aluminum Alloy",
    durability: "Corrosion Resistant",
    compatibility: "Fits most standard cars",
    assembly: "Professional installation recommended",
    color: "Silver, Black, Gunmetal",
    features: ["Lightweight", "Stylish Design", "Enhanced Performance", "Easy Maintenance"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "N/A"
  },
  {
    id: 2,
    images: ["/honda-civic-2019.png", "/honda-civic-2019.png", "/honda-civic-2019.png"],
    title: "Car Seat Covers",
    sub_title: "Premium PU Leather",
    feature1: "Waterproof",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 4,500",
    sub_price: "PKR 8,500",
    num: "Full Set",
    num2: "Universal",
    num3: "Premium",
    material: "Premium PU Leather",
    durability: "Waterproof",
    compatibility: "Fits all standard car seats",
    assembly: "DIY installation",
    color: "Available in black, gray, and beige",
    features: ["Waterproof", "Easy to Clean", "Comfortable", "Durable"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "Black/Gray/Beige"
  },
  {
    id: 3,
    images: ["/products/carDashboardCamera.jpg", "/products/carDashboardCamer2.jpg", "/products/carDashboardCamera1.jpg", "/products/dash-cam-mounted.jpg"],
    title: "Dashboard Camera",
    sub_title: "HD Recording",
    feature1: "Night Vision",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 8,500",
    sub_price: "PKR 12,000",
    num: "1080p HD",
    num2: "Wide Angle",
    num3: "Night Vision",
    material: "High-grade plastic",
    durability: "Heat resistant",
    compatibility: "Universal dashboard mount",
    assembly: "Easy suction cup installation",
    color: "Black",
    features: ["1080p Recording", "Night Vision", "Loop Recording", "G-Sensor"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "N/A"
  },
  {
    id: 4,
    images: ["/products/floor-mats-main.jpg", "/products/floor-mats-set.jpg", "/products/floor-mats-installed.jpg", "/products/floor-mats-detail.jpg"],
    title: "Car Floor Mats",
    sub_title: "All Weather",
    feature1: "Anti-Slip",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 3,200",
    sub_price: "PKR 4,500",
    num: "4 Piece Set",
    num2: "All Weather",
    num3: "Anti-Slip",
    material: "Heavy-duty rubber",
    durability: "Weather resistant",
    compatibility: "Universal fit for most vehicles",
    assembly: "Drop-in installation",
    color: "Black",
    features: ["Waterproof", "Easy to Clean", "Anti-Slip", "Custom Fit"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "Black"
  },
  {
    id: 7,
    images: ["/honda-civic-2019.png", "/honda-civic-2019.png", "/honda-civic-2019.png"],
    title: "Dashboard Camera",
    sub_title: "HD Recording",
    feature1: "Night Vision",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 120",
    sub_price: "PKR 150",
    num: "1080p HD",
    num2: "Wide Angle",
    num3: "Night Vision",
    material: "High-grade plastic",
    durability: "Heat resistant",
    compatibility: "Universal dashboard mount",
    assembly: "Easy suction cup installation",
    color: "Black",
    features: ["1080p Recording", "Night Vision", "Loop Recording", "G-Sensor"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "N/A"
  },
  {
    id: 8,
    images: ["/honda-civic-2019.png", "/honda-civic-2019.png", "/honda-civic-2019.png"],
    title: "Car Floor Mats",
    sub_title: "All Weather",
    feature1: "Anti-Slip",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 60",
    sub_price: "PKR 80",
    num: "4 Piece Set",
    num2: "All Weather",
    num3: "Anti-Slip",
    material: "Heavy-duty rubber",
    durability: "Weather resistant",
    compatibility: "Universal fit for most vehicles",
    assembly: "Drop-in installation",
    color: "Black",
    features: ["Waterproof", "Easy to Clean", "Anti-Slip", "Custom Fit"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "Black"
  },
  {
    id: 5,
    images: ["/honda-civic-2019.png", "/honda-civic-2019.png", "/honda-civic-2019.png"],
    title: "LED Headlights",
    sub_title: "Bright & Efficient",
    feature1: "Long Lasting",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 3,500",
    sub_price: "PKR 4,000",
    num: "6000K White",
    num2: "50W Power",
    num3: "Long Lasting",
    material: "Aluminum housing",
    durability: "50,000 hour lifespan",
    compatibility: "H4/H7/H11 bulb types",
    assembly: "Plug and play installation",
    color: "Cool White 6000K",
    features: ["Energy Efficient", "Bright Light", "Long Lasting", "Easy Install"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "N/A"
  },
  {
    id: 6,
    images: ["/products/seat-covers-main.jpg", "/products/seat-covers-black.jpg", "/products/seat-covers-gray.jpg", "/products/seat-covers-beige.jpg", "/products/seat-covers-detail.jpg"],
    title: "Car Seat Covers",
    sub_title: "Premium PU Leather",
    feature1: "Waterproof",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 4,500",
    sub_price: "PKR 8,500",
    num: "Full Set",
    num2: "Premium PU",
    num3: "Waterproof",
    material: "Premium PU Leather",
    durability: "Waterproof",
    compatibility: "Fits all standard car seats",
    assembly: "DIY installation",
    color: "Available in black, gray, and beige",
    features: ["Waterproof", "Easy to Clean", "Comfortable", "Durable", "Premium PU Leather"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "Black/Gray/Beige"
  },
  {
    id: 9,
    images: ["/honda-civic-2019.png", "/honda-civic-2019.png", "/honda-civic-2019.png"],
    title: "Car Body Cover",
    sub_title: "All Weather Protection",
    feature1: "Waterproof",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 90",
    sub_price: "PKR 120",
    num: "Universal Size",
    num2: "All Weather",
    num3: "Waterproof",
    material: "Heavy-duty polyester",
    durability: "UV and weather resistant",
    compatibility: "Universal fit for most vehicles",
    assembly: "Easy slip-on installation",
    color: "Silver",
    features: ["Waterproof", "UV Protection", "Breathable", "Elastic Hem"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "N/A"
  },
  {
    id: 10,
    images: ["/honda-civic-2019.png", "/honda-civic-2019.png", "/honda-civic-2019.png"],
    title: "GPS Navigation System",
    sub_title: "Smart Display",
    feature1: "Voice Commands",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 300",
    sub_price: "PKR 350",
    num: "7 Inch Display",
    num2: "Smart GPS",
    num3: "Voice Commands",
    material: "High-resolution LCD",
    durability: "Shock resistant",
    compatibility: "Universal dashboard mount",
    assembly: "Professional installation recommended",
    color: "Black",
    features: ["Voice Commands", "Real-time Traffic", "Offline Maps", "Bluetooth"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "N/A"
  },
  {
    id: 11,
    images: ["/honda-civic-2019.png", "/honda-civic-2019.png", "/honda-civic-2019.png"],
    title: "Portable Car Vacuum",
    sub_title: "Compact Cleaner",
    feature1: "Rechargeable",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 60",
    sub_price: "PKR 80",
    num: "120W Power",
    num2: "Compact",
    num3: "Rechargeable",
    material: "ABS plastic housing",
    durability: "Long-lasting battery",
    compatibility: "12V car outlet compatible",
    assembly: "Ready to use",
    color: "Black",
    features: ["Rechargeable", "Compact Design", "Strong Suction", "Multiple Attachments"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "N/A"
  },
  {
    id: 12,
    images: ["/honda-civic-2019.png", "/honda-civic-2019.png", "/honda-civic-2019.png"],
    title: "Car Battery Charger",
    sub_title: "Fast Charging",
    feature1: "12V/24V Support",
    rating: 4.5,
    price: "Price",
    amount_price: "PKR 100",
    sub_price: "PKR 130",
    num: "10A Output",
    num2: "Fast Charging",
    num3: "12V/24V Support",
    material: "Heavy-duty metal housing",
    durability: "Overcharge protection",
    compatibility: "12V and 24V batteries",
    assembly: "Clamp connection",
    color: "Red and Black",
    features: ["Fast Charging", "Overcharge Protection", "LED Indicators", "Portable"],
    engine: "N/A",
    auction_grade: "N/A",
    imported_year: "2024",
    mileage: "N/A",
    interior_color: "N/A"
  },
];

export default accessoriesData;